version: '3.1'
services:
  stats:
    build:
      context: ./stats/service
      dockerfile: ./Dockerfile
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - STATS_SERVER_URL=http://localhost:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=stats

  main:
    build:
      context: ./main
      dockerfile: ./Dockerfile
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - stats
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-service

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-service